apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.collector.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.collector.serviceName }}.{{ .Values.collector.namespace }}.svc.cluster.local
  ports:
{{- range .Values.collector.ports }}
    - name: port-{{ . }}
      port: {{ . }}
      protocol: TCP
{{- end }}
